[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8080
  publish = "build/client"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["react-router"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Range, X-Admin-Token, X-Admin-Auth"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    # Force compression
    Accept-Encoding = "gzip, br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
