[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build/client"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8888
  autoLaunch = false
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"

# Redirects
[[redirects]]
  from = "/cache-clear"
  to = "/cache-clear.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    # Force compression
    Accept-Encoding = "gzip, br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
