[build]
  publish = "build/client"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

# Fix MIME types et modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

# Redirects pour les routes React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["visitor"]}
    Accept-Encoding = "gzip, br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
    Cache-Control = "public, max-age=31536000, immutable"

# Compression
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    # Force compression
    Accept-Encoding = "gzip, br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
