[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8080
  publish = "build/client"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["react-router"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Range, X-Admin-Token, X-Admin-Auth"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
