[build]
  command = "npm run build && echo '/*    /index.html   200' > build/client/_redirects"
  functions = "netlify/functions"
  publish = "build/client"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8888
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"